version: "3.3"

services:
  web:
    image: mkanisetty/my-flask-app-image:latest
    ports:
      - "8001:8001"
    volumes:
      - my_flask_volume:/app

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=test@123"

volumes:
  my_flask_volume:
    external: true
